const express=require('express');const cors=require('cors');const{chromium}=require('playwright');
const app=express();app.use(cors());app.use(express.json({limit:'5mb'}));
const PORT=process.env.PORT||3000,TAMS_URL='http://www.tams.com.ar/organismos/vuelos.aspx';
const FAST=['AEP','EZE','MDQ','COR','MDZ','NQN','ROS'],DEEP=['AEP','EZE','MDQ','COR','MDZ','NQN','ROS','CRD','BRC','IGR','SLA','TUC','JUJ','RES','SDE','BHI','FTE','USH','RSA','SFN'];
const cache=new Map(),CACHE_MS=5*60*1000;
function nf(n){return String(n||'').toUpperCase().replace(/\s+/g,'').replace(/^AR/,'').replace(/\D/g,'')}
function isReg(s){return /^(LV|PR|CC|PS|PT|PP|CX|N)[A-Z0-9-]{2,8}$/i.test(String(s||'').replace(/-/g,''))}
function tok(t){return String(t||'').replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').split(/\s+/).filter(Boolean)}
function parse(text,airport,movement,win){const ts=tok(text),out=[];for(let i=0;i<ts.length-8;i++){const c=ts[i],num=ts[i+1];if(!/^[A-Z0-9]{2,3}$/.test(c)||!/^\d{3,4}$/.test(num))continue;let idx=i+2,scheduled='';if(/^\d{2}\/\d{2}$/.test(ts[idx])&&/^\d{2}:\d{2}$/.test(ts[idx+1])){scheduled=ts[idx]+' '+ts[idx+1];idx+=2}else continue;let registration='-',position='-';if(isReg(ts[idx])){registration=ts[idx].replace(/-/g,'');position=ts[idx+1]||'-';idx+=2}else{position=ts[idx]||'-';idx+=1}let r={company:c,flight:c+num,flightNumber:num,scheduled,registration,position,estimated:ts[idx]||'-',actual:ts[idx+1]||'-',terminal:ts[idx+2]||'-',sector:ts[idx+3]||'-',gateOrBelt:ts[idx+4]||'-',route:ts[idx+5]||'-',remark:ts[idx+6]||'-',sanidad:ts[idx+7]||'-',airport,movement,window:'+'+win+' horas',raw:ts.slice(i,Math.min(ts.length,idx+10))};if(!['Cía.','Vuelo','STD'].includes(r.company))out.push(r)}return out}
async function sel(selects,i,v){if(!selects[i])return;try{await selects[i].selectOption(String(v),{timeout:2500})}catch{try{await selects[i].evaluate((el,val)=>{el.value=String(val);el.dispatchEvent(new Event('change',{bubbles:true}))},String(v))}catch{}}}
async function buscar(page){for(const s of ['input[type="submit"]','input[value*="Buscar"]','button:has-text("Buscar")','text=Buscar']){try{const e=page.locator(s).first();if(await e.count()){await e.click({timeout:3000}).catch(()=>{});await page.waitForLoadState('networkidle',{timeout:6000}).catch(()=>{});return}}catch{}}}
async function q({airport='AEP',movement='PARTIDAS',window='6',flight}){const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:1280,height:900}});p.setDefaultTimeout(8000);await p.goto(TAMS_URL,{waitUntil:'domcontentloaded',timeout:15000});const selects=await p.locator('select').all();await sel(selects,0,movement==='ARRIBOS'?'A':'D');await sel(selects,1,airport);await sel(selects,5,window);await buscar(p);await p.waitForTimeout(1000);const text=await p.locator('body').innerText({timeout:8000});const rows=parse(text,airport,movement,window),f=nf(flight);return{airport,movement,window:'+'+window+' horas',matches:rows.filter(r=>r.flightNumber===f||r.flight==='AR'+f),rowsCount:rows.length}}finally{await b.close().catch(()=>{})}}
function plan({origin,destination,airport,deep}){const a=[];const add=(ap,m,w)=>{if(ap&&!a.some(x=>x.airport===ap&&x.movement===m&&x.window===w))a.push({airport:ap,movement:m,window:w})};if(origin){add(origin,'PARTIDAS','6');add(origin,'PARTIDAS','12')}if(destination){add(destination,'ARRIBOS','6');add(destination,'ARRIBOS','12')}if(airport){add(airport,'PARTIDAS','6');add(airport,'ARRIBOS','6');add(airport,'PARTIDAS','12');add(airport,'ARRIBOS','12')}if(!a.length){const aps=deep?DEEP:FAST,wins=deep?['6','12','24','48']:['6','12'];for(const ap of aps)for(const w of wins){add(ap,'PARTIDAS',w);add(ap,'ARRIBOS',w)}}return a}
app.get('/api/health',(_,res)=>res.json({ok:true,name:'tams-clean-stable-v1',time:new Date().toISOString()}));
app.get('/api/flight',async(req,res)=>{const number=nf(req.query.number);if(!number)return res.status(400).json({ok:false,error:'Falta number'});const origin=req.query.origin?String(req.query.origin).toUpperCase():'',destination=req.query.destination?String(req.query.destination).toUpperCase():'',airport=req.query.airport?String(req.query.airport).toUpperCase():'',deep=String(req.query.deep||'')==='1';const key=JSON.stringify({number,origin,destination,airport,deep});const ca=cache.get(key);if(ca&&Date.now()-ca.t<CACHE_MS)return res.json({...ca.data,cached:true});const checked=[],matches=[],start=Date.now();for(const item of plan({origin,destination,airport,deep})){if(Date.now()-start>(deep?45000:22000))break;checked.push(`${item.airport}-${item.movement}-+${item.window} horas`);try{const r=await q({...item,flight:number});if(r.matches.length){matches.push(...r.matches);break}}catch(e){checked.push('ERROR '+item.airport+' '+e.message.slice(0,60))}}
const best=matches[0];if(best&&(!best.registration||best.registration==='-')&&best.route&&/^[A-Z]{3}$/.test(best.route)){try{const ex=await q({airport:best.route,movement:'PARTIDAS',window:'12',flight:number});const wr=ex.matches.find(m=>m.registration&&m.registration!=='-');if(wr)best.registration=wr.registration}catch{}}
const data={ok:true,flight:'AR'+number,matchesCount:matches.length,matches,checked,updatedAt:new Date().toISOString()};cache.set(key,{t:Date.now(),data});res.json(data)});
app.listen(PORT,()=>console.log('TAMS clean backend escuchando en puerto '+PORT));
